version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://ye-meri-bucket-hai-codebuild-ki
      - aws cloudfront create-invalidation --distribution-id E2HTSDBGVHSWEH --paths "/*"
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
